# Generated by Django 5.1.4 on 2024-12-15 12:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0002_rename_capatity_event_capacity_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='registration',
            unique_together=set(),
        ),
        migrations.AlterField(
            model_name='registration',
            name='participant_name',
            field=models.CharField(max_length=255),
        ),
    ]
